/**
 * Every brand asset, from one drawing: a single cycle of a 50 Hz sine wave on
 * its baseline, ending in a live dot. Writes the web icons (SVG and PNG) and
 * the Android launcher, notification and splash resources.
 * Run: pnpm --filter @gridwatch/web icons
 */
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { launch } from './browser.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const icons = join(root, 'public', 'icons');
const res = join(root, 'android', 'app', 'src', 'main', 'res');

const C = { night: '#0a111d', sky: '#1b2a4b', wave: '#86a8ff', live: '#43c795', base: '#31415e' };

/** One sine cycle from x0 to x1 about cy, as a polyline path (works in SVG and Android pathData). */
function wave(x0, x1, cy, amp, steps = 48) {
  const pts = [];
  for (let i = 0; i <= steps; i++) {
    const t = i / steps;
    pts.push(`${(x0 + (x1 - x0) * t).toFixed(2)},${(cy - amp * Math.sin(t * Math.PI * 2)).toFixed(2)}`);
  }
  return `M${pts[0]} L${pts.slice(1).join(' ')}`;
}

/** The mark in a box of `size`, with the drawing scaled into the central `inner` fraction. */
function mark(size, inner, { stroke = C.wave, base = C.base, dot = C.live, weight = 0.058 } = {}) {
  const w = size * inner;
  const x0 = (size - w) / 2;
  const x1 = x0 + w;
  const cy = size / 2;
  const amp = w * 0.34;
  const sw = size * weight;
  return [
    `<line x1="${(x0 - sw * 0.6).toFixed(2)}" y1="${cy}" x2="${(x1 + sw * 0.6).toFixed(2)}" y2="${cy}" stroke="${base}" stroke-width="${(sw * 0.28).toFixed(2)}" stroke-linecap="round"/>`,
    `<path d="${wave(x0, x1, cy, amp)}" fill="none" stroke="${stroke}" stroke-width="${sw.toFixed(2)}" stroke-linecap="round" stroke-linejoin="round"/>`,
    `<circle cx="${x1.toFixed(2)}" cy="${cy}" r="${(sw * 0.95).toFixed(2)}" fill="${dot}"/>`,
  ].join('\n  ');
}

const background = (size, rx) =>
  `<defs><radialGradient id="sky" cx="50%" cy="0%" r="110%"><stop offset="0" stop-color="${C.sky}"/><stop offset="0.7" stop-color="${C.night}"/></radialGradient></defs>\n  <rect width="${size}" height="${size}" rx="${rx}" fill="url(#sky)"/>`;

const svg = (size, body) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}">\n  ${body}\n</svg>\n`;

// --- Web ------------------------------------------------------------------
writeFileSync(join(icons, 'icon.svg'), svg(512, `${background(512, 112)}\n  ${mark(512, 0.56)}`));
// Maskable: full bleed, drawing inside the 80% safe zone.
writeFileSync(join(icons, 'maskable.svg'), svg(512, `${background(512, 0)}\n  ${mark(512, 0.46)}`));
// Monochrome badge for web notifications.
writeFileSync(join(icons, 'badge.svg'), svg(72, mark(72, 0.7, { stroke: '#fff', base: '#fff', dot: '#fff', weight: 0.1 })));

// --- Android --------------------------------------------------------------
/** A VectorDrawable with a viewport of `size`, from the same geometry. */
function vector(size, dp, inner, { stroke, base, dot, weight }) {
  const w = size * inner;
  const x0 = (size - w) / 2;
  const x1 = x0 + w;
  const cy = size / 2;
  const sw = size * weight;
  const r = sw * 0.95;
  const baseline = base
    ? `    <path android:pathData="M${(x0 - sw * 0.6).toFixed(2)},${cy} L${(x1 + sw * 0.6).toFixed(2)},${cy}" android:strokeColor="${base}" android:strokeWidth="${(sw * 0.28).toFixed(2)}" android:strokeLineCap="round"/>\n`
    : '';
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by apps/web/scripts/render-icons.mjs. Edit the script, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${dp}dp"
    android:height="${dp}dp"
    android:viewportWidth="${size}"
    android:viewportHeight="${size}">
${baseline}    <path android:pathData="${wave(x0, x1, cy, w * 0.34)}" android:strokeColor="${stroke}" android:strokeWidth="${sw.toFixed(2)}" android:strokeLineCap="round" android:strokeLineJoin="round"/>
    <path android:pathData="M${(x1 - r).toFixed(2)},${cy} a${r.toFixed(2)},${r.toFixed(2)} 0 1,0 ${(2 * r).toFixed(2)},0 a${r.toFixed(2)},${r.toFixed(2)} 0 1,0 ${(-2 * r).toFixed(2)},0" android:fillColor="${dot}"/>
</vector>
`;
}

const write = (path, text) => {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
};

// Adaptive icon: 108dp canvas, content inside the 66dp safe circle.
write(join(res, 'drawable', 'ic_launcher_foreground.xml'), vector(108, 108, 0.4, { stroke: C.wave, base: C.base, dot: C.live, weight: 0.058 }));
// Notification icon: white on transparent (Android tints it).
write(join(res, 'drawable', 'ic_stat_hz.xml'), vector(24, 24, 0.74, { stroke: '#FFFFFFFF', base: null, dot: '#FFFFFFFF', weight: 0.1 }));
write(
  join(res, 'mipmap-anydpi-v26', 'ic_launcher.xml'),
  `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
    <monochrome android:drawable="@drawable/ic_launcher_foreground"/>
</adaptive-icon>
`,
);
write(join(res, 'mipmap-anydpi-v26', 'ic_launcher_round.xml'), readFileSync(join(res, 'mipmap-anydpi-v26', 'ic_launcher.xml'), 'utf8'));
write(
  join(res, 'values', 'ic_launcher_background.xml'),
  `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">${C.night}</color>
</resources>
`,
);
// Splash (Android 11 and earlier; 12+ uses the launcher icon): the mark on the night background.
write(
  join(res, 'drawable', 'splash.xml'),
  `<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/ic_launcher_background"/>
    <item android:drawable="@drawable/ic_launcher_foreground" android:gravity="center" android:width="160dp" android:height="160dp"/>
</layer-list>
`,
);
// Remove the template's image splash screens and old foreground bitmaps.
for (const dir of ['drawable', 'drawable-v24', ...['land', 'port'].flatMap((o) => ['mdpi', 'hdpi', 'xhdpi', 'xxhdpi', 'xxxhdpi'].map((d) => `drawable-${o}-${d}`))]) {
  rmSync(join(res, dir, 'splash.png'), { force: true });
}
rmSync(join(res, 'drawable-v24'), { recursive: true, force: true });
rmSync(join(res, 'drawable', 'ic_launcher_background.xml'), { force: true });

// --- Rasterise ------------------------------------------------------------
const densities = { mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 };
const jobs = [
  [join(icons, 'icon.svg'), join(icons, 'icon-192.png'), 192, false],
  [join(icons, 'icon.svg'), join(icons, 'icon-512.png'), 512, false],
  [join(icons, 'maskable.svg'), join(icons, 'maskable-512.png'), 512, false],
  [join(icons, 'maskable.svg'), join(icons, 'apple-touch-icon.png'), 180, false],
  [join(icons, 'badge.svg'), join(icons, 'badge-72.png'), 72, false],
  // Legacy launcher bitmaps for Android 7 (API 24-25), square and round.
  ...Object.entries(densities).flatMap(([d, scale]) => [
    [join(icons, 'icon.svg'), join(res, `mipmap-${d}`, 'ic_launcher.png'), 48 * scale, false],
    [join(icons, 'maskable.svg'), join(res, `mipmap-${d}`, 'ic_launcher_round.png'), 48 * scale, true],
  ]),
];
for (const d of Object.keys(densities)) rmSync(join(res, `mipmap-${d}`, 'ic_launcher_foreground.png'), { force: true });

const browser = await launch();
const page = await browser.newPage();
for (const [source, target, size, round] of jobs) {
  const markup = readFileSync(source, 'utf8').replace('<svg ', `<svg width="${size}" height="${size}" `);
  const clip = round ? 'border-radius:50%;overflow:hidden;' : '';
  await page.setViewportSize({ width: size, height: size });
  await page.setContent(`<html><body style="margin:0;background:transparent"><div style="width:${size}px;height:${size}px;${clip}">${markup}</div></body></html>`);
  mkdirSync(dirname(target), { recursive: true });
  await page.screenshot({ path: target, omitBackground: true, clip: { x: 0, y: 0, width: size, height: size } });
}
await browser.close();
console.log(`wrote ${jobs.length} bitmaps and the Android vector resources`);
